authentication/urls.py
from django.urls import path
from main.views import ScreenView
from authentication.views import LoginView, LogoutView, UpdateUserView


urlpatterns = [
    path(
        "user/profile/",
        ScreenView.as_view(screen="user-profile"),
        name="user-profile",
    ),
    path(
        "user/update/", UpdateUserView.as_view(), name="user-update"
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

gerenciador/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include(("main.urls", "main"), namespace="main")),
    path("", include(("https.urls", "https"), namespace="https")),
    path(
        "authentication/",
        include(("authentication.urls", "authentication"), namespace="authentication"),
    ),
    path(
        "financial/",
        include(("financial.urls", "financial"), namespace="financial"),
    ),
    path("admin/", admin.site.urls),
]

main/urls.py
from django.urls import path
from main.views import ScreenView

urlpatterns = [
    path("", ScreenView.as_view(screen="inicial"), name="inicial"),
]

templates/screens/user-profile.html
{% extends 'base.html' %}

{% block titulo %}Perfil do Usuário{% endblock titulo %}

{% block controles %}
	<div class="row">
		<div class="col-md-12" id="alertas"></div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="box box-default">
				<div class="box-header">
					<div class="box-title">Dados Pessoais</div>
				</div>

				<div class="box-body">

					<div class="row">
						<div class="col-md-1">Nome:</div>
						<div class="col-md-3"><input type="text" class="form-control" id="first_name" disabled value="{{request.user.first_name}}"></div>

						<div class="col-md-1">Sobrenome:</div>
						<div class="col-md-3"><input type="text" class="form-control" id="last_name" disabled value="{{request.user.last_name}}"></div>

						<div class="col-md-1">E-mail:</div>
						<div class="col-md-3"><input type="email" class="form-control" value="{{request.user.email}}" id="email"></div>
					</div>

					<div class="row" style="padding-top: 10px;">
						<div class="col-md-1">Senha:</div>
						<div class="col-md-3"><input type="password" class="form-control" id="password" placeholder="Senha"></div>

						<div class="col-md-1">Novamente:</div>
						<div class="col-md-3"><input type="password" class="form-control" id="password_confirmation" placeholder="Repita Senha"></div>

						<div class="col-md-3 col-md-offset-1">
							<a href="javascript:send_form()" class="btn btn-primary btn-flat" style="width: 100%;">
								<i class="fa fa-check">&nbsp;</i>Enviar
							</a>
						</div>
					</div>

				</div>

			</div>
		</div>
	</div>
{% endblock controles %}

{% block cabecalho %}{% endblock cabecalho %}

{% block processamento %}
	<script>
		function validate_form() {
			status = true
			if ($('#email').val() == '') { status = false }
			return status
		}

		function send_form() {
			if (valida_formulario()) {
				request_data = {
					email: $('#email').val(),
					password: $('#password').val(),
					password_confirmation: $('#password_confirmation').val()
				}

				$.post('{% url 'authentication:user-update' %}', request_data)
				.done(function(response) {
					if (response.status == 200) {
						swal({
							type: 'success',
							title: 'Dados atualizados com sucesso.'
						})
						.then(() => {window.location.reload()})
					} else {
						swal(
							'Erro',
							`Código: ${response.status}`,
							'error'
						)
					}
				})
				.fail(function() {
					swal(
						'Erro',
						'Recarregue a página e tente novamente.',
						'error'
					)
				})
			} else {
				swal(
					'Dados Incorretos',
					'Preencha os campos corretamente e tente de novo.',
					'warning'
				)
			}
		}
	</script>
{% endblock processamento %}