authentication/urls.py
from django.urls import path
from main.views import ScreenView
from authentication.views import LoginView, LogoutView, UpdateUserView


urlpatterns = [
    path(
        "user/profile/",
        ScreenView.as_view(screen="user-profile"),
        name="user-profile",
    ),
    path(
        "user/update/", UpdateUserView.as_view(), name="user-update"
    ),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

gerenciador/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include(("main.urls", "main"), namespace="main")),
    path("", include(("https.urls", "https"), namespace="https")),
    path(
        "authentication/",
        include(("authentication.urls", "authentication"), namespace="authentication"),
    ),
    path(
        "financial/",
        include(("financial.urls", "financial"), namespace="financial"),
    ),
    path("admin/", admin.site.urls),
]

main/urls.py
from django.urls import path
from main.views import ScreenView

urlpatterns = [
    path("", ScreenView.as_view(screen="inicial"), name="inicial"),
]

authentication/views/login_view.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.views import View


class LoginView(View):
    template_name = "login.html"

    def get(self, request):
        template = "base.html" if request.user.is_authenticated else "login.html"
        return render(request, template, {})

    def post(self, request):
        template = "login.html"
        user_authenticated = authenticate(
            username=request.POST.get("user"), password=request.POST.get("password")
        )

        if user_authenticated:
            if user_authenticated.is_active:
                login(request, user_authenticated)
                template = "base.html"
            else:
                messages.error(request, "Conta desabilitada :(")
        else:
            messages.error(request, "Usuário ou senha incorretos. Tente novamente.")

        return render(request, template)

templates/base.html
{% load static %}
{% load gravatar %}
<!DOCTYPE html>
<!--
	This is a starter template page. Use this page to start your new project from
	scratch. This page gets rid of all links and provides the needed markup only.
	-->
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Gerenciador - Mazzolli Sistemas</title>
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		<link rel="stylesheet" href="{% static 'bibliotecas/bootstrap/dist/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'bibliotecas/font-awesome/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'bibliotecas/Ionicons/css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/skins/skin-yellow.min.css' %}">
		<link rel="stylesheet"
			href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
		<link rel="stylesheet" href="{% static 'css/estilo.css' %}">

		{% block cabecalho %}{% endblock cabecalho %}
	</head>
	<!--
		BODY TAG OPTIONS:
		=================
		Apply one or more of the following classes to get the
		desired effect
		|---------------------------------------------------------|
		| SKINS         | skin-blue                               |
		|               | skin-black                              |
		|               | skin-purple                             |
		|               | skin-yellow                             |
		|               | skin-red                                |
		|               | skin-green                              |
		|---------------------------------------------------------|
		|LAYOUT OPTIONS | fixed                                   |
		|               | layout-boxed                            |
		|               | layout-top-nav                          |
		|               | sidebar-collapse                        |
		|               | sidebar-mini                            |
		|---------------------------------------------------------|
		-->
	<body class="hold-transition skin-yellow sidebar-mini">
		<div class="wrapper">
			<!-- Main Header -->
			<header class="main-header">
				<!-- Logo -->
				<a href="{% url 'main:inicial' %}" class="logo">
					<!-- mini logo for sidebar mini 50x50 pixels -->
					<span class="logo-mini">MS</span>
					<!-- logo for regular state and mobile devices -->
					<span class="logo-lg">Mazzolli Sistemas</span>
				</a>
				<!-- Header Navbar -->
				<nav class="navbar navbar-static-top" role="navigation">
					<!-- Sidebar toggle button-->
					<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
					</a>
					<!-- Navbar Right Menu -->
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<!-- User Account Menu -->
							<li class="dropdown user user-menu">
								<!-- Menu Toggle Button -->
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<!-- The user image in the navbar-->
									<img src="{{request.user.email|gravatar_url:40}}" class="user-image">
									<!-- hidden-xs hides the username on small devices so only the image appears. -->
									<span class="hidden-xs">{{request.user.get_full_name}}</span>
								</a>
								<ul class="dropdown-menu">
									<!-- The user image in the menu -->
									<li class="user-header">
										<img src="{{request.user.email|gravatar_url:100}}" class="img-circle">
										<p>
											{{request.user.get_full_name}}
											<small>Membro desde {{request.user.date_joined|date:'SHORT_DATE_FORMAT'}}</small>
										</p>
									</li>
									<!-- Menu Footer-->
									<li class="user-footer">
										<div class="pull-left">
											<a href="{% url 'authentication:user-profile' %}" class="btn btn-default btn-flat">Perfil</a>
										</div>
										<div class="pull-right">
											<a href="{% url 'authentication:logout' %}" class="btn btn-default btn-flat">Sair</a>
										</div>
									</li>
								</ul>
							</li>
							<!-- Control Sidebar Toggle Button -->
							<li>
								<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
							</li>
						</ul>
					</div>
				</nav>
			</header>
			<!-- Left side column. contains the logo and sidebar -->
			<aside class="main-sidebar">
				<!-- sidebar: style can be found in sidebar.less -->
				<section class="sidebar">
					<!-- Sidebar user panel (optional) -->
					<div class="user-panel">
						<div class="pull-left image">
							<img src="{{request.user.email|gravatar_url:100}}" class="img-circle">
						</div>
						<div class="pull-left info">
							<p>{{request.user.get_full_name}}</p>
							<!-- Status -->
							<a href="{% url 'authentication:logout' %}"><i class="fa fa-circle text-danger"></i> Sair</a>
						</div>
					</div>
					<!-- Sidebar Menu -->
					<ul class="sidebar-menu" data-widget="tree">
						<li class="header">PRINCIPAL</li>
						<li class="active"><a href="{% url 'main:inicial' %}"><i class="fa fa-home"></i> <span>Inicial</span></a></li>

							{% if perms.financeiro %}<li class="header">FINANCEIRO</li>{% endif %}
							{% if perms.financeiro.view_contasareceber %}<li><a href="{% url 'financeiro:contas-a-receber' %}"><i class="fa fa-reply"></i> <span>Contas a Receber</span></a></li>{% endif %}
							{% if perms.financeiro.view_contasapagar %}<li><a href="{% url 'financeiro:contas-a-pagar' %}"><i class="fa fa-share"></i> <span>Contas a Pagar</span></a></li>{% endif %}
							{% if perms.financeiro.view_fluxodecaixa %}<li><a href="{% url 'financeiro:fluxo-de-caixa' %}"><i class="fa fa-money"></i> <span>Fluxo de Caixa</span></a></li>{% endif %}
					</ul>

					<!-- <ul class="sidebar-menu" data-widget="tree">
						<li class="header">PRINCIPAL</li>
						<li class="active"><a href="#"><i class="fa fa-home"></i> <span>Inicial</span></a></li>
						<li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
						<li class="treeview">
							<a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
							<span class="pull-right-container">
							<i class="fa fa-angle-left pull-right"></i>
							</span>
							</a>
							<ul class="treeview-menu">
								<li><a href="#">Link in level 2</a></li>
								<li><a href="#">Link in level 2</a></li>
							</ul>
						</li>
					</ul> -->
					<!-- /.sidebar-menu -->
				</section>
				<!-- /.sidebar -->
			</aside>
			<!-- Content Wrapper. Contains page content -->
			<div class="content-wrapper">
				<!-- Content Header (Page header) -->
				<section class="content-header">
					<h1>
						{% block titulo %}
							Inicial
							<small>Resumo das Atividades</small>
						{% endblock titulo %}
					</h1>
					{% block breadcrumb %}
						<!--<ol class="breadcrumb">
						<li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
						<li class="active">Here</li>
					</ol>-->
					{% endblock breadcrumb %}
					{% include "includes/messages.html" with messages=messages %}
				</section>
				<!-- Main content -->
				<section class="content container-fluid">
					{% block controles %}
						<!--------------------------
						| Your Page Content Here |
						-------------------------->
					{% endblock controles %}
				</section>
				<!-- /.content -->
			</div>
			<!-- /.content-wrapper -->
			<!-- Main Footer -->
			<footer class="main-footer">
				<!-- To the right -->
				<div class="pull-right hidden-xs">
					Todos os direitos reservados.
				</div>
				<!-- Default to the left -->
				<strong>Copyright &copy; 2021 <a href="http://www.mazzollisistemas.com.br" target="_blank">Mazzolli Sistemas</a></strong>
			</footer>
			<!-- Control Sidebar -->
			<aside class="control-sidebar control-sidebar-dark">
				<!-- Create the tabs -->
				<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
					<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
					<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
					<!-- Home tab content -->
					<div class="tab-pane active" id="control-sidebar-home-tab">
						<!--<h3 class="control-sidebar-heading">Recent Activity</h3>
						<ul class="control-sidebar-menu">
							<li>
								<a href="javascript:;">
									<i class="menu-icon fa fa-birthday-cake bg-red"></i>
									<div class="menu-info">
										<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
										<p>Will be 23 on April 24th</p>
									</div>
								</a>
							</li>
						</ul> -->
						<!-- /.control-sidebar-menu -->
						<h3 class="control-sidebar-heading">Tarefas em Andamento</h3>
						<ul class="control-sidebar-menu">
							<li>
								<a href="javascript:;">
									<h4 class="control-sidebar-subheading">
										Exemplo de tarefa
										<span class="pull-right-container">
										<span class="label label-warning pull-right">70%</span>
										</span>
									</h4>
									<div class="progress progress-xxs">
										<div class="progress-bar progress-bar-warning" style="width: 70%"></div>
									</div>
								</a>
							</li>
						</ul>
						<!-- /.control-sidebar-menu -->
					</div>
					<!-- /.tab-pane -->
					<!-- Stats tab content -->
					<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
					<!-- /.tab-pane -->
					<!-- Settings tab content -->
					<div class="tab-pane" id="control-sidebar-settings-tab">
						<form method="post">
							<h3 class="control-sidebar-heading">Configurações Gerais</h3>
							<div class="form-group">
								<label class="control-sidebar-subheading">
								Opção 1
								<input type="checkbox" class="pull-right" checked>
								</label>
								<p>
									Informação a respeito da opção 1
								</p>
							</div>
							<!-- /.form-group -->
						</form>
					</div>
					<!-- /.tab-pane -->
				</div>
			</aside>
			<!-- /.control-sidebar -->
			<!-- Add the sidebar's background. This div must be placed
				immediately after the control sidebar -->
			<div class="control-sidebar-bg"></div>
		</div>
		<!-- ./wrapper -->
		<!-- REQUIRED JS SCRIPTS -->
		<!-- jQuery 3 -->
		<script src="{% static 'bibliotecas/jquery/dist/jquery.min.js' %}"></script>
		<!-- Bootstrap 3.3.7 -->
		<script src="{% static 'bibliotecas/bootstrap/dist/js/bootstrap.min.js' %}"></script>
		<!-- Moment.JS -->
		<script src="{% static 'bibliotecas/momentjs/moment.min.js' %}"></script>
		<!-- AdminLTE App -->
		<script src="{% static 'js/adminlte.min.js' %}"></script>
		<!-- Optionally, you can add Slimscroll and FastClick plugins.
			Both of these plugins are recommended to enhance the
			user experience. -->

		<script src="{% static 'bibliotecas/sweetalert2/sweetalert2-all.min.js' %}"></script>

		{% block processamento %}{% endblock processamento %}

	</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mazzolli Sistemas - Gerenciamento Interno</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bibliotecas/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bibliotecas/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bibliotecas/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'bibliotecas/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Gerenciador</b>&nbsp;MS
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Faça o seu login para entrar</p>

    {% if messages %}
      {% for message in messages %}
        <div style="color: red">{{message}}</div>{% if not forloop.last %}<br/>{% endif %}
      {% endfor %}
    {% endif %}

    <form action="{% url 'authentication:login' %}" id="signin-form_id" method="POST">
		{% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Usuário" name="user">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Senha" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
		  <div class="col-xs-12 text-center">
			  <input type="submit" value="Login" class="btn btn-primary btn-block btn-flat">
		  </div>
      </div>
    </form>

    <a href="#">Esqueci minha senha</a><br>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bibliotecas/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bibliotecas/bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>